### ISSUE TITLE
Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by julienbechade** [creynders/grunt-generate-configs#1]
Hi,

First thing first, thanks for automatizing this step. Very helpful.  
The `inquirer` module isn't bundle with your module so you get the error—in the title—when running the `generate_configs` task.  

`npm install inquirer` in your module directory is enough to fix the problem but this extra step isn't obvious to everyone.

Cheers.

**Comment by Althafnash** [comment]
thanx
